# Generated by Django 4.1.7 on 2023-04-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
