# Generated by Django 4.1.7 on 2023-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM1', '0005_tag_order_customer_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='CRM1.tag'),
        ),
    ]
